sensor:
  - platform: template
    sensors:
      bleach_tank:
        friendly_name: "Bleach tank"
        value_template: "{{ states('input_number.bleach_tank')|round(2)}}"

  - platform: history_stats
    name: bleach_on_last_hour
    entity_id: switch.orp
    state: 'on'
    type: time
    end: '{{now().replace(minute=0).replace(second=0)}}'
    duration: 01:00:00

  - platform: history_stats
    name: bleach_on_last_48h
    entity_id: switch.orp
    state: 'on'
    type: time
    end: '{{now()}}'
    duration: 48:00:00

input_number:
  bleach_tank:
    min: 0
    max: 76
    step: 0.1
    unit_of_measurement: 'l'
    icon: mdi:blood-bag
    name: Chlorine Tank
    mode: box
  bleach_concentration:
    min: 0
    max: 15
    step: .25
    unit_of_measurement: '%'
    icon: mdi:water-percent
  bleach_speed:
    min: 0
    max: 263
    step: 1
    unit_of_measurement: 'ml/min'
    icon: mdi:needle
    mode: box
  notify_bleach_high:
    name: Chlorine Overfeed
    min: 0
    max: 15.2
    step: 0.1
    unit_of_measurement: 'l/48h'
  notify_bleach_tank:
    name: Chlorine Tank Low
    min: 0
    max: 8
    step: 0.1
    unit_of_measurement: 'l'
    icon: mdi:flask-empty-outline
  bleach_inject:
    min: 0
    max: 10000
    step: 1
    unit_of_measurement: 'ml'
    icon: mdi:beaker
    mode: box

automation:

  # Bleach Section
  - alias: bleach_every_hour
    trigger:
    - platform: time_pattern
      minutes: 1
    condition: []
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bleach_tank
        value: " {{ [0, ( states('input_number.bleach_tank')|float - ( states('sensor.bleach_on_last_hour')|float * states('input_number.bleach_speed')|int * 6 / 100 ) )] | max | round(2) }} "

  - alias: bleach_tank_low
    trigger:
      platform: template
      value_template: >-
        {% if states('input_number.notify_bleach_tank')|int > 0 and (states('input_number.bleach_tank')|float < states('input_number.notify_bleach_tank')|float) %}
          true
        {% endif %}
    condition: []
    action:
    - data_template:
        title: "Chlorine Tank Low!"
        message: >-
          {{states('input_number.bleach_tank')|float}} liters left!
      service: notify.notify

  - alias: bleach_high
    trigger:
      platform: template
      value_template: >-
        {% if states('input_number.notify_bleach_high')|float> 0 and
               states('sensor.bleach_on_last_48h')|float * states('input_number.bleach_speed')|float * 60 / 1000 > states('input_number.notify_bleach_high')|float %}
          true
        {% endif %}
    condition: []
    action:
    - entity_id: switch.orp
      service: switch.turn_off
    - entity_id: input_boolean.lock_bleach
      service: input_boolean.turn_on
    - data_template:
        title: "Bleach Injection Blocked!"
        message: >-
          {{states('input_number.notify_bleach_high')|float|round(1)}} liters in 48h!
      service: notify.notify

  - alias: bleach_set
  # TODO figure out this formula, needs documentation 
    trigger: []
    condition: []
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bleach_inject
        value: " {{ ( states('input_number.capacity_metric')|float * ( states('input_number.fc_target')|float - states('sensor.e_fc')|float ) * (100 / states('input_number.bleach_concentration')|float ), 0)|max |round(0)|int }} "

  - alias: bleach_inject
    trigger: []
    condition: []
    action:
    - condition: state
      entity_id: input_boolean.lock_bleach
      state: 'off'
    - condition: state
      entity_id: switch.Pump
      state: 'on'
    - condition: numeric_state
      entity_id: input_number.bleach_inject
      value_template: "{{ states('input_number.bleach_inject')|float / states('input_number.capacity_metric')|float }}"
      above: 5.0
      below: 200.0
    - entity_id: switch.orp
      service: switch.turn_on
    - data_template:
        title: "Chlorine Injection Start"
        message: >-
          Adding {{states('input_number.bleach_inject')|float|round(0)}} ml
      service: notify.notify
    - delay: 00:00:{{ [0 , 60 * states('input_number.bleach_inject')|float/ states('input_number.bleach_speed')|float ]|max|int }}
    - entity_id: switch.orp
      service: switch.turn_off
    - data_template:
        title: "Chlorine Injection Ended"
        message: Pump ran for {{ [0 , states('input_number.bleach_inject')|float/ states('input_number.bleach_speed')|float ]|max|int }} minutes
      service: notify.notify
