sensor:
  - platform: template
    sensors:
      muriatic_tank:
        friendly_name: "Acid tank"
        value_template: "{{ states('input_number.muriatic_tank')|round(2)}}"

  - platform: history_stats
    name: muriatic_on_last_hour
    entity_id: switch.ph
    state: 'on'
    type: time
    end: '{{now().replace(minute=0).replace(second=0)}}'
    duration: 01:00:00

  - platform: history_stats
    name: muriatic_on_last_48h
    entity_id: switch.ph
    state: 'on'
    type: time
    end: '{{now()}}'
    duration: 48:00:00


input_number:
  muriatic_tank:
    min: 0
    max: 76
    step: 0.1
    unit_of_measurement: 'l'
    icon: mdi:blood-bag
    name: Acid Tank
    mode: box
  muriatic_concentration:
    min: 0
    max: 30
    step: .1
    unit_of_measurement: '%'
    icon: mdi:water-percent
  muriatic_speed:
    min: 10
    max: 750
    step: 10
    unit_of_measurement: 'ml/min'
    icon: mdi:needle
    mode: box
  notify_muriatic_high:
    name: Acid Overfeed
    min: 0
    max: 15.2
    step: 0.1
    unit_of_measurement: 'l/48h'
  notify_muriatic_tank:
    name: Acid Tank Low
    min: 0
    max: 8
    step: 0.1
    unit_of_measurement: 'l'
    icon: mdi:flask-empty-outline
  muriatic_inject:
    min: 0
    max: 10000
    step: 1
    unit_of_measurement: 'ml'
    icon: mdi:beaker
    mode: box

automation:

  # Muriatic Section
  - alias: muriatic_every_hour
    trigger:
    - platform: time_pattern
      minutes: 1
    condition: []
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.muriatic_tank
        value: " {{ [0, (states('input_number.muriatic_tank')|float - ( states('sensor.muriatic_on_last_hour')|float * states('input_number.muriatic_speed')|int * 6 / 100 ))]|max | round(2) }} "

  - alias: muriatic_tank_low
    trigger:
      platform: template
      value_template: >-
        {% if states('input_number.notify_muriatic_tank')|int > 0 and (states('input_number.muriatic_tank')|float < states('input_number.notify_muriatic_tank')|float) %}
          true
        {% endif %}
    condition: []
    action:
    - data_template:
        title: "Muriatic Tank Low!"
        message: >-
          {{states('input_number.muriatic_tank')|float}} liters left!
      service: notify.notify

  - alias: muriatic_high
    trigger:
      platform: template
      value_template: >-
        {% if states('input_number.notify_muriatic_high')|float> 0 and
               states('sensor.muriatic_on_last_48h')|float * states('input_number.muriatic_speed')|float * 60 / 1000 > states('input_number.notify_muriatic_high')|float %}
          true
        {% endif %}
    condition: []
    action:
    - entity_id: switch.ph
      service: switch.turn_off
    - entity_id: input_boolean.lock_muriatic
      service: input_boolean.turn_on
    - data_template:
        title: "Acid Injection Blocked!"
        message: >-
          {{states('input_number.notify_muriatic_high')|float|round(1)}} in 48h!
      service: notify.notify

  - alias: muriatic_set
  # called when the pump starts, or when the ph target changes
  # TODO figure out this formula, needs documentation
    trigger: []
    condition: []
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.muriatic_inject
        value: " {{ ( states('input_number.capacity_metric')|float * ( 10 ** (8 - states('input_number.ph_target')|float ) - 10 ** (8 - states('sensor.ph')|float ) ) * (126.19 / states('input_number.muriatic_concentration')|float ),0 )|max |round(0)|int }} "

  - alias: muriatic_inject
    trigger: []
    condition: []
    action:
    - condition: state
      entity_id: input_boolean.lock_muriatic
      state: 'off'
    - condition: state
      entity_id: switch.Pump
      state: 'on'
    - condition: numeric_state
      entity_id: input_number.muriatic_inject
      value_template: "{{ states('input_number.muriatic_inject')|float / states('input_number.capacity_metric')|float }}"
      above: 5.0
      below: 100.0
    - entity_id: switch.ph
      service: switch.turn_on
    - data_template:
        title: "Acid Injection Start"
        message: >-
          Adding {{states('input_number.muriatic_inject')|float|round(0)}} ml
      service: notify.notify
    - delay: 00:00:{{ [0 , 60 * states('input_number.muriatic_inject')|float/ states('input_number.muriatic_speed')|float ]|max|int }}
    - entity_id: switch.ph
      service: switch.turn_off
    - data_template:
        title: "Acid Injection Ended"
        message: Pump ran for {{ [0 , states('input_number.muriatic_inject')|float/ states('input_number.muriatic_speed')|float ]|max|int }} minutes
      service: notify.notify
