sensor:
# Atlas Resistance Temperature Detector (RTD)
  - platform: atlas_scientific
# For serial ports use:
#   port: /dev/ttyUSB0
# For I2C enter the hex device id
    port: 0x66
    scan_interval: 30
    scale: 'F'

  - platform: statistics
    name: pool_temp_stat
    entity_id: sensor.ezo_temperature

  - platform: template
    sensors:
      pool_temp:
        unit_of_measurement: 'C'
        value_template: >
          {% if is_state('sensor.pool_temp_stat', 'unknown') %}
            0
          {% else %}
            {{ states('sensor.pool_temp_stat') }}
          {% endif %}
      solar_pump_on:
        value_template: >
          {{ states.input_boolean.solar_pump_on.state }}
      solar_pump_running:
        value_template: >
          {{ states.input_boolean.solar_pump_running.state }}
      seconds_since_solar_pump_start:
        value_template: >
          {{ (now().timestamp() - states.input_boolean.solar_pump_on.last_changed.timestamp()) | int }}
      distance_from_window_boundary_div:
        value_template: >-
          {{ (( states('sensor.seconds_since_solar_pump_start') | float ) / ( states('input_number.temp_check_window') | float )) | int }}
      distance_from_window_boundary_mod:
        value_template: >-
          {{ (( states('sensor.seconds_since_solar_pump_start') | float ) % ( states('input_number.temp_check_window') | float )) | int }}


# When does pump start
# if time since switch.pool_solar_pump state change to on is temp_check_window

# When does pump stop
# if time since last switch.pool_solar_pump state change to on is greater than temp_check_delay
# and binary_sensor.pool_temp_threshold is off


input_number:
  calibrate_temp:
    min: 40
    max: 90
    step: 1
    unit_of_measurement: 'F'
    icon: mdi:coolant-temperature
    mode: box
    initial: 70
  temp_range_low:
    min: 20
    max: 35
    step: .5
    unit_of_measurement: 'C'
    icon: mdi:coolant-temperature
    initial: 25
  temp_range_high:
    min: 20
    max: 35
    step: .5
    unit_of_measurement: 'C'
    icon: mdi:coolant-temperature
    initial: 28
  temp_check_delay:
    min: 30
    max: 300
    step: 1
    unit_of_measurement: 'seconds'
    icon: mdi:clock-start
    initial: 300
  temp_check_window:
    min: 30
    max: 120
    step: 30
    unit_of_measurement: 'minutes'
    icon: mdi:repeat
    initial: 60

input_boolean:
  solar_pump_active:
    initial: true
  solar_pump_on:
    initial: false
  solar_pump_running:
    initial: false

binary_sensor:

  - platform: threshold
    entity_id: sensor.pool_temp_stat
    lower: 25
    upper: 28
    name: pool_temp_threshold

#automation:
#  - alias: Solar Pump On
#    trigger:
#      - platform: state
#        entity_id: sensor.solar_pump_on
#        to: true
#        action:
#          - entity_id: switch.pool_solar
#            service: switch.turn_on
#  - alias: Solar Pump Off
#    trigger:
#      - platform: state
#        entity_id: sensor.solar_pump_on
#        to: false
#        action:
#          - entity_id: switch.pool_solar
#            service: switch.turn_off
