sensor:
# Atlas Resistance Temperature Detector (RTD)
  - platform: atlas_scientific
    port: 0x6E # 110
    name: 'pool_temperature'
    scan_interval: 10

# Atlas Resistance Temperature Detector (RTD)
  - platform: atlas_scientific
    port: 0x66 # 102
    name: 'roof_temperature'
    scan_interval: 10

  - platform: statistics
    name: pool_temp_stat
    entity_id: sensor.pool_temperature
    state_characteristic: mean
    sampling_size: 6

  - platform: statistics
    name: roof_temp_stat
    entity_id: sensor.roof_temperature
    state_characteristic: mean
    sampling_size: 6

template:
  - sensor:
      - name: pool_temp
        unit_of_measurement: 'C'
        state: >
          {% if is_state('sensor.pool_temperature', 'unknown') %}
            0
          {% else %}
            {{ states('sensor.pool_temperature') }}
          {% endif %}
      - name: roof_temp
        unit_of_measurement: 'C'
        state: >
          {% if is_state('sensor.roof_temperature', 'unknown') %}
            0
          {% else %}
            {{ states('sensor.roof_temperature') }}
          {% endif %}
      - name: temp_check_window
        state: >
          {{ states('input_number.temp_check_window') | float  }}
      - name: temp_check_delay
        state: >
          {{ states('input_number.temp_check_delay') | float }}
      - name: minutes_since_solar_pump_change
        state: >
          {{ (((now().timestamp() | float) - (states.input_boolean.solar_pump_on.last_changed.timestamp() | float)) / 60) | int }}
      - name: distance_from_window_boundary
        state: >-
          {{ (( states('sensor.minutes_since_solar_pump_change') | float ) % ( states('input_number.temp_check_window') | float)) | int }}
      - name: temp_range_low
        state: >-
          {{ (states('input_number.temp_range_low') | float) }}
      - name: temp_range_high
        state: >-
          {{ (states('input_number.temp_range_high') | float) }}
      - name: pool_temp_float
        state: >-
          {{ (states('sensor.pool_temp') | float) }}

  - binary_sensor:
      - name: pool_temp_threshold
        state: >
          {{ ((((states('input_number.temp_range_low') | float) < (states('sensor.pool_temp') | float)) and ((states('input_number.temp_range_high') | float) > (states('sensor.pool_temp') | float) )))}}
      - name: pool_temp_to_high
        state: >
          {{ (states('input_number.temp_range_high') | float) < (states('sensor.pool_temp') | float) }}
      - name: pool_temp_to_low
        state: >
          {{ (states('input_number.temp_range_low') | float) > (states('sensor.pool_temp') | float) }}
      - name: pool_temp_higher_than_roof_temp
        state: >
          {{ (states('sensor.roof_temp') | float) < (states('sensor.pool_temp') | float) }}
      - name: pool_temp_check
        state: >
          {{ (states('sensor.temp_check_delay') | float) < (states('sensor.distance_from_window_boundary') | float) }}
      - name: on_window
        state: >
          {{ states('sensor.distance_from_window_boundary') | int == 0 }}
      - name: turn_solar_pump_off
        state: >-
          {{ is_state('binary_sensor.pool_temp_check','on') and (is_state('binary_sensor.pool_temp_to_high','on') or is_state('sensor.pool_temp_higher_than_roof_temp', 'on') ) }}
      - name: solar_pump_running
        state: >-
          {{ states('input_boolean.solar_pump_running') }}
      - name: dummy_pump
        state: >-
          {{ states('input_boolean.dummy_pump') }}


input_number:
  calibrate_temp:
    min: 40
    max: 90
    step: 1
    unit_of_measurement: 'F'
    icon: mdi:coolant-temperature
    mode: box
    initial: 70
  temp_range_low:
    min: 20
    max: 35
    step: .5
    unit_of_measurement: 'C'
    icon: mdi:coolant-temperature
    initial: 20
  temp_range_high:
    min: 20
    max: 35
    step: .5
    unit_of_measurement: 'C'
    icon: mdi:coolant-temperature
  temp_check_delay:
    min: 1
    max: 15
    step: 1
    unit_of_measurement: 'minutes'
    icon: mdi:clock-start
  temp_check_window:
    min: 1
    max: 120
    step: 1
    unit_of_measurement: 'minutes'
    icon: mdi:repeat

input_boolean:
  solar_heat_mode:
    initial: false
  solar_pump_on:
    initial: false
  solar_pump_maint:
    initial: false
  solar_pump_running:
    initial: false
  dummy_pump:
    initial: false

automation:
  - alias: Solar Pump On
    trigger:
      - platform: template
        value_template: "{{ is_state('binary_sensor.on_window', 'on') and is_state('input_boolean.solar_pump_on', 'on') and is_state('input_boolean.solar_pump_running', 'off') }}"
    condition: []
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.solar_pump_running
  - alias: Solar Pump Off
    trigger:
      - platform: template
        value_template: "{{ is_state('binary_sensor.pool_temp_check','on') and is_state('binary_sensor.pool_temp_threshold','off') }}"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.solar_pump_running

  - alias: Solar Pump Off Imediate
    trigger:
      - platform: template
        value_template: "{{ is_state('input_boolean.solar_pump_on', 'off') }}"
    condition: []
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.solar_pump_running

  - alias: Solar Pump Maint On Imediate
    trigger:
      - platform: template
        value_template: "{{ is_state('input_boolean.solar_pump_maint', 'on') }}"
    condition: []
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.solar_pump_running

  - alias: Solar Pump Maint Off Imediate
    trigger:
      - platform: template
        value_template: "{{ is_state('input_boolean.solar_pump_maint', 'off') }}"
    condition: []
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.solar_pump_running

  - alias: Real Solar Pump On
    trigger:
      - platform: template
        value_template: "{{ is_state('binary_sensor.solar_pump_running','on') }}"
    condition: []
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.dummy_pump
      - service: valve.open_valve
        target:
          entity_id: valve.pool_solar_pump_water


  - alias: Real Solar Pump Off
    trigger:
      - platform: template
        value_template: "{{ is_state('binary_sensor.solar_pump_running','off') }}"
    condition: []
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.dummy_pump
      - service: valve.close_valve
        target:
          entity_id: valve.pool_solar_pump_water
